name: gatk4
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=main
  - aioeasywebdav=2.4.0=py36_1000
  - aiohttp=3.5.4=py36h7b6447c_0
  - appdirs=1.4.3=py36h28b3542_0
  - asn1crypto=0.24.0=py36_0
  - async-timeout=3.0.1=py36_0
  - attrs=19.1.0=py36_1
  - bamtools=2.5.1=he860b03_5
  - bcrypt=3.1.6=py36h7b6447c_0
  - bedtools=2.28.0=hdf88d34_0
  - binutils_impl_linux-64=2.28.1=had2808c_3
  - blas=1.0=mkl
  - boto3=1.9.162=py_0
  - botocore=1.12.163=py_0
  - bwa=0.7.17=h84994c4_5
  - bzip2=1.0.7=h7b6447c_0
  - ca-certificates=2019.5.15=0
  - cachetools=2.1.0=py_0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.6.16=py36_0
  - cffi=1.12.3=py36h2e261b9_0
  - chardet=3.0.4=py36_1
  - click=7.0=py36_0
  - colormath=3.0.0=py_2
  - configargparse=0.14.0=py36_0
  - cryptography=2.7=py36h1ba5d50_0
  - curl=7.64.1=hbc83047_0
  - cycler=0.10.0=py36_0
  - datrie=0.7.1=py36h7b6447c_1
  - dbus=1.13.6=h746ee38_0
  - decorator=4.4.0=py36_1
  - docutils=0.14=py36_0
  - dropbox=9.3.0=py36_0
  - expat=2.2.6=he6710b0_0
  - fastqc=0.11.8=1
  - filechunkio=1.8=py_2
  - font-ttf-dejavu-sans-mono=2.37=h6964260_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - ftputil=3.4=py_0
  - future=0.17.1=py36_0
  - gatk4=4.1.2.0=1
  - gcc_impl_linux-64=7.2.0=habb00fd_3
  - gitdb2=2.0.5=py36_0
  - gitpython=2.1.11=py36_0
  - glib=2.56.2=hd408876_0
  - google-api-core=1.13.0=py36_0
  - google-auth=1.6.3=py_0
  - google-cloud-core=1.0.2=py_0
  - google-cloud-storage=1.16.1=py_0
  - google-resumable-media=0.3.2=py_0
  - googleapis-common-protos=1.5.10=py36_0
  - graphite2=1.3.13=h23475e2_0
  - graphviz=2.40.1=h21bd128_2
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - harfbuzz=1.8.8=hffaf4a1_0
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py36_0
  - idna_ssl=1.1.0=py36_0
  - intel-openmp=2019.4=243
  - jinja2=2.10.1=py36_0
  - jmespath=0.9.4=py_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.0.1=py36_0
  - kiwisolver=1.1.0=py36he6710b0_0
  - krb5=1.16.1=h173b8e3_7
  - libcurl=7.64.1=h20c2e04_0
  - libdeflate=1.0=h14c3975_1
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.8.0=hd408876_0
  - libsodium=1.0.16=h1bed415_0
  - libssh2=1.8.2=h1ba5d50_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - lzstring=1.0.4=py_1001
  - markdown=3.1.1=py36_0
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib=3.1.0=py36h5429711_0
  - mkl=2019.4=243
  - mkl_fft=1.0.12=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - multidict=4.5.2=py36h7b6447c_0
  - multiqc=1.7=py_4
  - ncurses=6.1=he6710b0_1
  - networkx=2.3=py_0
  - numpy=1.16.4=py36h7e9f1db_0
  - numpy-base=1.16.4=py36hde5b4d6_0
  - openjdk=8.0.152=h46b5887_1
  - openssl=1.1.1c=h7b6447c_1
  - pandas=0.24.2=py36he6710b0_0
  - pango=1.42.4=h049681c_0
  - paramiko=2.4.2=py36_0
  - pcre=8.43=he6710b0_0
  - perl=5.26.2=h14c3975_0
  - picard=2.20.2=0
  - pigz=2.4=h84994c4_0
  - pip=19.1.1=py36_0
  - pixman=0.38.0=h7b6447c_0
  - prettytable=0.7.2=py_3
  - protobuf=3.8.0=py36he6710b0_0
  - psutil=5.6.3=py36h7b6447c_0
  - pyasn1=0.4.5=py_0
  - pyasn1-modules=0.2.4=py36_0
  - pycparser=2.19=py36_0
  - pygraphviz=1.3=py36h14c3975_1
  - pynacl=1.3.0=py36h7b6447c_0
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.4.0=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - pyrsistent=0.14.11=py36h7b6447c_0
  - pysftp=0.2.9=py_1
  - pysocks=1.7.0=py36_0
  - python=3.6.8=h0371630_0
  - python-dateutil=2.8.0=py36_0
  - python-irodsclient=0.7.0=py_0
  - pytz=2019.1=py_0
  - pyyaml=5.1.1=py36h7b6447c_0
  - qt=5.9.7=h5867ecd_1
  - ratelimiter=1.2.0=py36_1000
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py36_0
  - rsa=3.4.2=py_1
  - s3transfer=0.2.0=py36_0
  - samtools=1.9=h8571acd_11
  - setuptools=41.0.1=py36_0
  - simplejson=3.16.0=py36h14c3975_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.12.0=py36_0
  - smmap2=2.0.5=py36_0
  - snakemake=5.5.1=0
  - snakemake-minimal=5.5.1=py_0
  - spectra=0.0.11=py_1
  - sqlite=3.28.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.3=py36h7b6447c_0
  - trimmomatic=0.39=1
  - urllib3=1.24.2=py36_0
  - wheel=0.33.4=py36_0
  - wrapt=1.11.2=py36h7b6447c_0
  - xmlrunner=1.7.7=py_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - yarl=1.3.0=py36h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
prefix: /home/jc502059/local/miniconda3/envs/gatk4

